-- 052: a school can now pay Chronix for its own platform subscription online, by card,
-- through Paystack — the piece CLAUDE.md's Platform billing section has said, since
-- migration 046, is "not built yet, deliberately": checkout and webhooks.
--
-- THE TRUST MODEL (same one routes/feesPublic.ts uses for parent fee payments, carried
-- over deliberately rather than re-invented): a payment's identity — which school, which
-- subscription, how much it owes — is resolved from a row THIS SERVER wrote before ever
-- talking to Paystack, keyed by a reference THIS SERVER generated
-- (apps/api/src/routes/platformBilling.ts, POST .../checkout). The webhook and the browser
-- callback (apps/api/src/routes/platformBillingPublic.ts) look that row up by `reference`
-- and never read `school_id` or `subscription_id` out of Paystack's metadata — metadata is
-- an unauthenticated caller's input twice over (the webhook's body, and the callback's
-- query string) and must never be trusted to say whose payment this is or what it was for.
--
-- WHY A NEW TABLE AND NOT A COLUMN ON platform_subscriptions. amount_naira on that table
-- is derived and overwritten by the trigger from migrations 044/045 on every write — it is
-- not safe to freeze a value there. A checkout and the webhook/callback that settles it can
-- straddle an enrolment change (a student added mid-flow recomputes amount_naira), and
-- [MOSES]'s decision carried over from the manual-recording flow is explicit: "No late
-- payment policy, still same amount as per students" — what is charged is rate × currently
-- enrolled students, with no proration and no exception for timing. So the amount a payer
-- is actually charged is the one read off platform_subscriptions AT THE MOMENT OF CHECKOUT,
-- snapshotted here in kobo (doctrine 11) so it cannot drift under the row that initiated it.
-- plan and billing_cycle are snapshotted alongside it for the same reason — what the row
-- says a payer was asked to pay for the subscription as it stood at checkout, not as it
-- might stand by the time Paystack confirms.
--
-- STATUS IS WRITE-ONCE, ENFORCED BY THE UPDATE, NOT A TRIGGER. The settlement query in
-- db/queries/platformBilling.ts is `UPDATE ... SET status = 'consumed' ... WHERE id = $1
-- AND status = 'pending'`. A webhook delivered twice, or a webhook racing the browser
-- callback for the same reference (routes/feesPublic.ts's own comment: "the webhook
-- usually wins this race") finds zero rows the second time and is told so by the affected
-- row count — the same shape feesPublic.ts gets from recordPayment's `duplicate` flag,
-- without a second table lock or a unique-violation catch. No DB trigger was added for
-- this because the one state transition that matters (pending -> consumed, exactly once)
-- is already exactly what a conditional UPDATE guarantees; a trigger here would duplicate
-- that guarantee, not strengthen it.
--
-- NOT PLAN = 'trial'. A trial school is not billed (migrations 044/045: trial is always
-- ₦0.00) and [MOSES]'s decision stands: "trial schools are free until trial ends" — there
-- is nothing for a trial school to check out for, so the checkout route itself refuses a
-- trial subscription (409 TRIAL_NOT_BILLABLE) before any row here is ever written.
--
-- subscription_id, not just school_id: school_id is kept too (every tenant-data table
-- carries it, per Migrations in CLAUDE.md, and it is what the export/deletion ratchets and
-- RLS key on) but subscription_id is what ties a payment to the specific plan/cycle it was
-- raised against, in case a school's subscription is ever replaced rather than updated.
--
-- RLS: mirrors platform_subscriptions (migration 017) and platform_pricing_config
-- (migration 044) — a super_admin-only authenticated policy, plus the service_role_bypass
-- every new table needs (Migrations, CLAUDE.md). This is Chronix's own commercial record of
-- a school's payment to Chronix, not the school's data, so — like platform_subscriptions —
-- it is not given a tenant (school_id = jwt school_id) policy; the API never reads this
-- table through anything but the service-role pool connection anyway (doctrine 2).
--
-- scripts/sql/rls_policy_inventory.txt is updated by hand in this commit to the policies
-- this migration creates. It could not be regenerated against a live database (no local
-- Postgres in this environment) — scripts/sql/rls_drift_check.sql must be run against
-- production after this migration ships, per the existing instruction for exactly this
-- situation (CLAUDE.md, Migrations, doctrine 14).

CREATE TABLE IF NOT EXISTS platform_subscription_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id UUID NOT NULL REFERENCES schools(id),
  subscription_id UUID NOT NULL REFERENCES platform_subscriptions(id),
  -- Generated by THIS server (crypto.randomUUID() in routes/platformBilling.ts) before
  -- Paystack is ever called, and the only thing the webhook/callback trust to find this row.
  reference TEXT NOT NULL UNIQUE,
  -- Snapshot at checkout time, kobo (doctrine 11) — never recomputed once written.
  amount_kobo BIGINT NOT NULL CHECK (amount_kobo > 0),
  plan TEXT NOT NULL,
  billing_cycle TEXT NOT NULL CHECK (billing_cycle IN ('monthly', 'termly', 'annual')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'consumed', 'failed')),
  initiated_by UUID NOT NULL REFERENCES users(id),
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE platform_subscription_payments IS
  'A school paying Chronix for its own platform subscription via Paystack. reference is generated here, before Paystack is called, and is the ONLY key the webhook/callback use to resolve which school and subscription a payment was for — never Paystack metadata (migration 052).';

CREATE INDEX IF NOT EXISTS idx_platform_subscription_payments_school
  ON platform_subscription_payments(school_id);
CREATE INDEX IF NOT EXISTS idx_platform_subscription_payments_subscription
  ON platform_subscription_payments(subscription_id);
-- The webhook and callback both resolve by reference; status filters the staff-facing
-- "pending payments" view this migration does not itself add a route for yet.
CREATE INDEX IF NOT EXISTS idx_platform_subscription_payments_status
  ON platform_subscription_payments(status);

ALTER TABLE platform_subscription_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS platform_subscription_payments_super_admin ON platform_subscription_payments;
CREATE POLICY platform_subscription_payments_super_admin ON platform_subscription_payments
  FOR ALL TO authenticated
  USING ((auth.jwt() ->> 'role')::text = 'super_admin');

DROP POLICY IF EXISTS service_role_bypass ON platform_subscription_payments;
CREATE POLICY service_role_bypass ON platform_subscription_payments
  FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON platform_subscription_payments TO authenticated, service_role;

-- End of migration 052
